### ISSUE TITLE
[❌ ] Failed to download patcho. Check tweakpatcher.log for more information.

### ISSUE THREAD

**Issue by Awalchahal** [Defying/TweakPatcher#22]

**Comment by Tippa181** [comment]
I'm having the same problem.

**Comment by chhaugen** [comment]
ghostbin.com is down, where it downloads patcho from.
(https://ghostbin.com/paste/ejjej/raw)

**Comment by VictorSerban47** [comment]
Yep. I tried everything...but this is the problem...someone know if this will be up again? :(

**Comment by Tippa181** [comment]
okay thanks time to play the wighting game ^.^

**Comment by chhaugen** [comment]
There is an alternative way.
you could compile it manualy using the original link (http://www.tonymacx86.com/general-help/86205-patcho-simple-hex-binary-patcher.html).
1. Open Textedit and create new document.
2. Go to Format -> Make plain text.
3. Copy the code from the orginal link into Textedit.
4. Save as main.c, and put it in the patch folder.
5. In Terminal, `cd [drag in the patch folder]` , and press enter.
6. `gcc main.c -o patcho`, press enter

Then you should have a file called patcho in the patch folder
1. delete main.c

**Comment by VictorSerban47** [comment]
Not working...I created the patcho file and it says (when I do what EverythingApplePro said) that it did't found it and it can't download it...

**Comment by chhaugen** [comment]
hmmm...
I'm currently at school, and i tried to remember what i did this morning.
Edit: and i also followed EverythingApplePro.

**Comment by VictorSerban47** [comment]
It's ghostbin.com going to be up again? Or wtf? :/

**Comment by chhaugen** [comment]
Try edit the script with Textedit and swap out the ghostbin.com link with http://pastebin.com/raw/JCKN9qCX

Edit: Please, let me know if it worked :smile:

**Comment by Tippa181** [comment]
thanks carlhen

**Comment by VictorSerban47** [comment]
[❌ ] Failed to build patcho. Check tweakpatcher.log for more information.

This is now way.... :((((

**Comment by chhaugen** [comment]
Try with a fresh download of TweakPatcher

**Comment by VictorSerban47** [comment]
WORKED!!!!!

**Comment by VictorSerban47** [comment]
I REPLACED IT  STUPIDLY!!! THANKS SO MUCH DUDEEEEEEEE

**Comment by VictorSerban47** [comment]
WHOAAAA...I'm going now to do what remained. :D

**Comment by chhaugen** [comment]
😄 Happy saving-your-friends-snaps-without-them-knowing

**Comment by miftahananta35** [comment]
it still doesnt work

**Comment by chhaugen** [comment]
So you downloaded a fresh copy, swaped out the ghostbin link with http://pastebin.com/raw/JCKN9qCX in the script with Textedit, and followed [EverythingApplePro](https://www.youtube.com/watch?v=l9o9rFTycwE) from here right?

**Comment by VictorSerban47** [comment]
Ok...now i messed up a few times by forgetting to put the sapchat in the folder...but now i finally reached when it says to install the app on my iphone and it doesn't install it...i need to delete some certificates from key chain...I have some things there from iPAWiND...XD

**Comment by VictorSerban47** [comment]
I need to do it all again....dang it................ ://///////

**Comment by chhaugen** [comment]
_crosses fingers_

**Comment by len2307** [comment]
where do i swap out the links?

**Comment by chhaugen** [comment]
Open tweakpatcher.sh with TextEdit, and look for a ghostbin.com link. Then swap it out. :smiley:

**Comment by len2307** [comment]
how do i open it?

**Comment by chhaugen** [comment]
Right click the file, open with (i think), and either click on TextEdit or click other

**Comment by len2307** [comment]
there's no open as just open

**Comment by chhaugen** [comment]
sorry, open with

**Comment by len2307** [comment]
not that either

**Comment by chhaugen** [comment]
![image](http://media02.hongkiat.com/mac-remove-duplicate-right-click-menus/duplicate-apps-removed.jpg) 
like this right?
just textedit (if it's there) instead

**Comment by len2307** [comment]
yep but i only have open, open without isnt there

**Comment by chhaugen** [comment]
Lets try another way to do it.
Open TextEdit first

**Comment by len2307** [comment]
yes

**Comment by chhaugen** [comment]
![image](https://cloud.githubusercontent.com/assets/8987475/14424438/54b26700-ffe1-11e5-967f-6b1e11575807.png)

**Comment by chhaugen** [comment]
then open and choose the script

**Comment by len2307** [comment]
<img width="735" alt="screen shot 2016-04-11 at 8 33 42 pm" src="https://cloud.githubusercontent.com/assets/18395251/14424498/be73222c-0024-11e6-80ef-e253a46e50af.png">

**Comment by pocadot99** [comment]
hi Carlhen, but i'm having the same problems nothing is working for me and i have followed all of your steps, what do I do?

**Comment by VictorSerban47** [comment]
Ok. I can't believe....I did the whole process 29 times...I counted. XDXD FINALLLY!!!!...I kept deleting profiles, forgetting to put 9.3.1 at the iOS version...and many stupid things... But now I just need to launch the app on my 6S Plus. Thanks so much @carlhen !!! If you have any social media (Twitter, Facebook...etc.) give them to me and we'll talk about some things...because you're obviously a PRO!
THANKS!!!!!!!

**Comment by chhaugen** [comment]
@len2307 choose tweakpatcher.sh

**Comment by chhaugen** [comment]
@VictorSerban47 You're welcome
Edit: I'm not that often on ether Facebook or twitter.

**Comment by chhaugen** [comment]
@pocadot99 could you please be a little more specific.

**Comment by len2307** [comment]
cant find the link

**Comment by chhaugen** [comment]
@len2307 try cmd + F, then search for ttps://ghostbin.com/paste/ejjej/raw

**Comment by pocadot99** [comment]
Sure, I have dowloaded a fresh TweakPatcher, that didn't work, I tried manually, that didn't work and i don't understand what i have done wrong

**Comment by len2307** [comment]
what you mean?

**Comment by chhaugen** [comment]
@pocadot99 What does the Terminal say?

**Comment by chhaugen** [comment]
@len2307 nevermind the top part
![image](https://cloud.githubusercontent.com/assets/8987475/14424741/26750e04-ffe3-11e5-9742-55c2cd300ce8.png)

**Comment by len2307** [comment]
thanks

**Comment by chhaugen** [comment]
I'm sorry, got to go. Back 15:15 (gmt +1)

**Comment by pocadot99** [comment]
It says "Failed to Download patcho. Cjeck Tweakpatcher.log for more information

**Comment by pocadot99** [comment]
![screen shot 2016-04-11 at 12 07 38](https://cloud.githubusercontent.com/assets/18395474/14425297/0bc84634-ffde-11e5-807b-083f1e9f57cf.png)
it has glitched out here, is that normal?

**Comment by chhaugen** [comment]
Try one more time. Download a fresh copy, and swap the links. From here you follow EverythingApplePro (link above) 😄

**Comment by chhaugen** [comment]
@VictorSerban47 Twitter: @CarlHenHau

**Comment by VictorSerban47** [comment]
I've added you. I'm GAME VIC on Twitter. (VIC --> Victor...that's obvious) :D

**Comment by Defying** [comment]
I've updated the script to switch from ghostbin to pastebin. https://github.com/Defying/TweakPatcher/commit/7327a02a40c8f9cd3104705a7f08806855ac1914

closing this issue

**Comment by pocadot99** [comment]
@carlhen it's still at that screen man, whats the issue?

**Comment by Defying** [comment]
@pocadot99 try redownloading the script, see if it fixes your issue

**Comment by pocadot99** [comment]
i've tried everything man it just stops there for some reason @Defying

**Comment by taiyo555** [comment]
Still having an issue downloading patho. Need help please @carlhen

**Comment by pocadot99** [comment]
@carlhen how do you re-download the script?

**Comment by taiyo555** [comment]
It just says patcho failed to download @carlhen

**Comment by fexy123** [comment]
PROBLEM: i wrote my apple ID in xcode and clicked fix issue, and it says: No decives. Creating a profile requires having a device registered in the Member Center.

i have created a profile at Member Center and still doenst work.

**Comment by JRaddd** [comment]
What am i doing wrong?
Jarods-MBP:~ jarodhoover$ cd/Users/jarodhoover/Desktop/TweakPatcher-master 
-bash: cd/Users/jarodhoover/Desktop/TweakPatcher-master: No such file or directory
Jarods-MBP:~ jarodhoover$ ./tweakpatcher.sh patch snapplus Snapchat.ipa
-bash: ./tweakpatcher.sh: No such file or directory
Jarods-MBP:~ jarodhoover$

**Comment by Defying** [comment]
@JRaddd you didn't run the `cd` command correctly.

`cd /Users/jarodhoover/Desktop/TweakPatcher-master`
